source 'https://rubygems.org'
ruby '1.9.3'

gem 'connection_pool'
gem 'gmail_xoauth'
gem 'json'
gem 'oauth2'
gem 'redis'
gem 'redis-namespace'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'uuid'
